theme: minima
title: Statistics Rules!!!
author: Carlos Parra Rojas
email: caeparraro@unal.edu.co
description: > # this means to ignore newlines until "baseurl:"
  I'm usually a sad person, but I'm working in changing my state of mind.

# social links
twitter_username: CarloRock # DO NOT include the @ character, or else the build will fail!
github_username:  CarloRockStats # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
